seed_everything: 333

model:
  class_path: lightning_modules.models.ts_interactive_model.TSInteractiveModel
  init_args:
    extractor:
      class_path: evaluators.extraction_evaluators.GPQAExtractionPromptingEvaluator
      init_args:
        app_name: 8B_grpc
        model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
        request_timeout: 300
        rater_temp: 0.0
        max_tokens: 32
    raters+:
      - class_path: evaluators.match_evaluators.GPQAMatchEvaluator
        init_args: {}
    max_turns: 1

data:
  class_path: lightning_modules.datasets.ts_gpqa_dataset.GPQATSDataModule
  init_args:
    train_batch_size: 1
    val_batch_size: 1_000_000
    val_max_instances: 1_000_000
    val_set_init_args:
      file_path: data/gpqa/gpqa_main.jsonl
      student_instruction: simple_cot
      teacher_instruction: simple_cot
