regime:
    _set_:
      num_steps: 1000
      num_data_epochs: 20
      checkpoint_every_n_steps: 200
      keep_last_n_checkpoints: 5
      keep_last_n_models: 10
      publish_metrics_every_n_steps: 5
common:
  metric_recorders:
      wandb:
        _set_:
          enabled: true
          project: ts-finetuning
