common:
  metric_recorders:
    wandb:
      _set_:
        run: ts_sft_8b_test
dataset:
  _set_:
    max_num_tokens: 8192
    max_num_valid_tokens: 8192
    max_seq_len: 8192
    path: __put_your_own_file_here__
    source_encode_mode: as_is
lr_scheduler:
  config:
    _set_:
      final_lr: 1.0e-08
      final_lr_scale: null
      num_warmup_steps: 100
model:
  _set_:
    name: llama3_1_8b_instruct
optimizer:
  config:
    _set_:
      betas:
      - 0.9
      - 0.95
      eps: 1.0e-08
      lr: 1.0e-07
      weight_decay: 0.1
regime:
  _set_:
    num_steps: 200
